#!/bin/bash
## cut-the-game
## version 0.0.1 - initial
##################################################
banner() {
  cat << EOF
                                             tttt          
                                          ttt:::t          
                                          t:::::t          
                                          t:::::t          
    ccccccccccccccccuuuuuu    uuuuuuttttttt:::::ttttttt    
  cc:::::::::::::::cu::::u    u::::ut:::::::::::::::::t    
 c:::::::::::::::::cu::::u    u::::ut:::::::::::::::::t    
c:::::::cccccc:::::cu::::u    u::::utttttt:::::::tttttt    
c::::::c     cccccccu::::u    u::::u      t:::::t          
c:::::c             u::::u    u::::u      t:::::t          
c:::::c             u::::u    u::::u      t:::::t          
c::::::c     cccccccu:::::uuuu:::::u      t:::::t    tttttt
c:::::::cccccc:::::cu:::::::::::::::uu    t::::::tttt:::::t
 c:::::::::::::::::c u:::::::::::::::u    tt::::::::::::::t
  cc:::::::::::::::c  uu::::::::uu:::u      tt:::::::::::tt
    cccccccccccccccc    uuuuuuuu  uuuu        ttttttttttt  
THE GAME
v0.0.1

EOF
}
game-over() {
  cat << EOF

 ::::::::     :::    ::::    :::: :::::::::::::::::: :::     ::::::::::::::::::::::  
:+:    :+:  :+: :+:  +:+:+: :+:+:+:+:      :+:    :+::+:     :+::+:       :+:    :+: 
+:+        +:+   +:+ +:+ +:+:+ +:++:+      +:+    +:++:+     +:++:+       +:+    +:+ 
:#:       +#++:++#++:+#+  +:+  +#++#++:++# +#+    +:++#+     +:++#++:++#  +#++:++#:  
+#+   +#+#+#+     +#++#+       +#++#+      +#+    +#+ +#+   +#+ +#+       +#+    +#+ 
#+#    #+##+#     #+##+#       #+##+#      #+#    #+#  #+#+#+#  #+#       #+#    #+# 
 ######## ###     ######       #####################     ###    #############    ### 
EOF
}
lost() {
  cat << EOF

It appears that you have lost your way ...
EOF
}
egg() {
  cat << EOF
##################################################
##############/   \\##############################
###########/         \############################
##########/     ^     \###########################
#########/   ^         \##########################
########/        \      | ########################
#######|  ^   ^  \\     | ########################
#######|        \\\\    / ########################
####### \  ^   \\\     / X########################
######## \            /  #########################
######### \\        //  X#########################
#########__-^^^^^^^^-___########################NS
:::::::::::::::::::::::::.........................
EOF
}
egg-in-a-meadow() {
  cat << EOF

$( test ${egg_count} -gt 0 && echo -n "Deep in" || echo -n "In" ) a meadow ${meadow}
far far away. $( test ${egg_count} -gt 0 && echo -n "The" || echo -n "A" ) cautious rabbit hides $( test ${egg_count} -gt 0 && echo -n "another" || echo -n "a" ) precious egg ${egg}.

Find the egg.

EOF
}
easter-egg() {
  echo "${meadow}" \
  | grep -e '[0-9]*' -o \
  | sort \
  | uniq -c \
  | sort -n \
  | head -1 \
  | cut '-d ' '-f8-'
}
meadow() {
  cat /dev/random \
  | xxd -ps \
  | head -1 \
  | sed \
    -e 's/0/_/g' \
    -e 's/a/,/g' \
    -e 's/b/|/g' \
    -e 's/c/;/g' \
    -e 's/d/:/g' \
    -e 's/e/^/g' \
    -e 's/f/$/g' 
}
cut-the-game() {
  local -i egg_count
  egg_count=0
  banner
  read -p "press enter key to start"
  while :
  do
    meadow=$( meadow )
    egg=$( easter-egg )
    egg-in-a-meadow
    while :
    do
     read -n 1 -p "cut '-d" delimiter
     echo -n "' -f" 
     read fields
     test "${delimiter}" || { lost ; game-over ; return ; }
     test "${fields}" || { lost ; game-over ; return ; }
     meadow=$( echo "${meadow}" | cut "-d${delimiter}" "-f${fields}" )
     echo -e "\n${meadow}\n"
     test ! "${meadow}" = "${egg}" || {
       echo -e "\nYou found the egg!\n"
       egg
       egg_count+=1
       echo -n -e "\nYou now have ${egg_count} egg$( test ! ${egg_count} -gt 1 || echo -n s ).\n" 
       echo -e "\nIt appears that the rabbit left behind some tracks."
       echo -e "\nDo you follow the rabbit deeper into the meadow to uncover more eggs? "
       read 
       case ${REPLY} in
        y|yes) break ;;
	n|no) true
       esac
       return
     }
     test ! $( echo "${meadow}" | grep -e "${egg}" | wc -w ) -eq 0 || {
       lost
       game-over
       return
     }
    done
  done
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
cut-the-game
##################################################
## generated by create-stub2.sh v0.1.2
## on Thu, 26 Sep 2019 20:57:02 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
