#!/bin/bash
## pure-bash-shuf
## version 0.0.1 - initial
##################################################
pure-bash-shuf() {
  local line
  local -a lines
  while read -r line
  do
   lines[RANDOM]=${line}
  done
  for line in ${lines[@]} 
  do
   echo ${line}
  done
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
pure-bash-shuf
##################################################
## generated by create-stub2.sh v0.1.2
## on Sun, 17 Nov 2019 21:43:24 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
