#!/bin/bash
## run-windirstat
## version 0.0.1 - initial
##################################################
. ${SH2}/aliases/commands.sh
candidate-executables() {
  echo -e /{a..z}/Program\ Files{,\ \(x86\)}/WinDirStat/"windirstat.exe\n"
}
try-run-windirstat() {
  candidate-executables | 
  xargs -i bash ${0} test-path "{}" 
}
run-windirstat-test-path() { { local windirstat ; windirstat="${@}" ; }
  test ! -f "${windirstat}" || "${windirstat}" "${path}"
}
run-windirstat-main() { { local -x path ; path="${@}" ; }
  try-run-windirstat 
}
run-windirstat() {
  commands
}
##################################################
if [ ! ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
run-windirstat ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on Fri, 28 Jun 2019 13:39:27 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
