#!/bin/bash
## test-pipeline-time2
## version 0.0.1 - initial
##################################################
func() { read -t ${t} input
  time -p {
    echo ${input-1} 1>&2
    sleep 1
    echo $(( ${input-1} + 1 ))
  }
}
test-pipeline-time2() {
  t=0 ; time echo 1 | func | func | func
  t=1 ; time echo 1 | func | func | func
  t=2 ; time echo 1 | func | func | func
  t=3 ; time echo 1 | func | func | func
  t=4 ; time echo 1 | func | func | func
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-pipeline-time2
##################################################
## generated by create-stub2.sh v0.1.2
## on Tue, 23 Jul 2019 22:13:53 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
