#!/bin/bash
## test-time-format
## version 0.0.1 - initial
##################################################
test-time-format() {
  echo "timing sleep 1 (default behavior) ..."
  time sleep 1
  echo "timing sleep 1 (portable) ..."
  time -p sleep 1 
  echo "timing sleep 1 (custom) ..."
  TIMEFORMAT=$'\nreal\t%0R\nuser\t%0U\nsys\t%0S\ncpu\t%P'
  time sleep 1
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-time-format
##################################################
## generated by create-stub2.sh v0.1.2
## on Mon, 22 Jul 2019 21:12:31 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
