#!/bin/bash
## test-function-positional-parameter-default-values
## version 0.0.1 - initial
##################################################
test-function-positional-parameter-default-values() { { local a ; a="${1-a}" ; local b ; b="${2-b}" ; }
  echo ${a}
  echo ${b}
}
##################################################
if [ ! ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-function-positional-parameter-default-values ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on Mon, 15 Jul 2019 15:41:40 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
