#!/bin/bash
## test-builtins
## version 0.0.1 - initial
##################################################
builtins() { 
  cat << EOF
alias 
bind 
builtin
caller 
command 
declare 
echo 
enable 
help 
let 
local 
logout 
mapfile 
printf 
read 
readarray 
source 
type 
typeset 
ulimit 
unalias 
EOF
} 
generate-disable-builtins-script() {
 local builtin
 test ! -f "script" || rm -v ${_} 1>/dev/null
  for builtin in $( builtins )
  do
   echo "${builtin}() { true ; }" >> script
  done
}
test-builtins() {
  generate-disable-builtins-script
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-builtins
##################################################
## generated by create-stub2.sh v0.1.2
## on Wed, 28 Aug 2019 13:45:00 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
