#!/bin/bash
## test-pipeline-mapfile
## version 0.0.1 - initial
##################################################
test-pipeline-mapfile() {
  #shopt -s lastpipe
  declare -a arr
  seq 10 | mapfile arr
  echo ${#arr[@]}
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-pipeline-mapfile
##################################################
## generated by create-stub2.sh v0.1.2
## on Thu, 25 Jul 2019 22:28:47 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
