#!/bin/bash
## test-pipeline-standard
## version 0.0.1 - initial
##################################################
upper() { { local str ; read str ; }
  echo error in upper 1>&2
  echo ${str^^}
}
lower() { { local str ; read str ; }
  echo error in lower 1>&2
  echo ${str,,}
}
test-pipeline-standard() {
  echo ${@} | lower | upper
}
##################################################
if [ ! ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-pipeline-standard ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on Tue, 23 Jul 2019 13:28:31 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
