#!/bin/bash
## test-temp
## version 0.0.1 - initial
##################################################
test-temp() {
  test "${temp}" && {
    temp=_${temp}
  } || {
    declare -x temp
    temp=$( mktemp )
  }
  declare -p temp 1>&2
  test ! $(( ${RANDOM} % 5 )) -eq 0 || { true ; return ; }
  bash ${0} 
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-temp
##################################################
## generated by create-stub2.sh v0.1.2
## on Tue, 16 Jul 2019 15:05:34 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
