#!/bin/bash
## test-ssl-cert-renewal-downtime
## version 0.0.2 - continue on exit code 60 else break
##################################################
test-ssl-cert-renewal-downtime() {
  date
  while :
  do
    sleep 5
    echo -n "."
    curl -v ${url} 1>/dev/null 
    test ${?} -eq 60 || break
    # false
  done
  date
  echo elapsed time: ${SECONDS} seconds
}
##################################################
if [ ${#} -eq 1 ] 
then
 url="${1}"
else
 exit 1 # wrong args
fi
##################################################
test-ssl-cert-renewal-downtime
##################################################
## generated by create-stub2.sh v0.1.2
## on Thu, 13 Jun 2019 09:16:04 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
