#!/bin/bash
## test-temp2
## version 0.0.1 - initial
##################################################
. ${SH2}/cecho.sh	# colored echo
. ${SH2}/temp.sh	# temp
test-temp2() {
  cecho white $( declare -p temp )
  cecho yellow "this: $( temp this )"
  cecho yellow "super: $( temp super )"
  cecho yellow "global: $( temp global )"
  test ! $(( ${RANDOM} % 5 )) -eq 0 || { true ; return ; }
  bash ${0} 
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-temp2
##################################################
## generated by create-stub2.sh v0.1.2
## on Tue, 16 Jul 2019 15:05:34 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
