#!/bin/bash
## test-pipeline-negation2
## version 0.0.1 - initial
##################################################
func() {
  echo -n ${1} 1>&2
  test ! $(( RANDOM % 10 )) -eq 0 
  return
}
test-pipeline-negation2() {
  set -o pipefail
  local -i i=1
  while :
  do
   ! func $(( ${i} % 10 )) | func $(( ( i + 1 ) % 10 )) | func $(( ( i - 1 ) % 10 )) && break
   i+=1
  done
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
time test-pipeline-negation2
##################################################
## generated by create-stub2.sh v0.1.2
## on Wed, 24 Jul 2019 13:20:10 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
