#!/bin/bash
## test-map-functions
## version 0.0.1 - initial
##################################################
square() { { local -i n ; n=${1} ; }
  echo $(( n * n ))
}
map() { { local function_name ; function_name="${1}" ;  }
  local car cdr
  read -t 1 car cdr
  test "${car}" || { true ; return ; }
  ${function_name} ${car} 
  echo ${cdr} | ${FUNCNAME} ${function_name}
}
test-map-functions() {
  seq 10 | xargs | map square
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
time test-map-functions
##################################################
## generated by create-stub2.sh v0.1.2
## on Sat, 27 Jul 2019 21:13:45 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
