#!/bin/bash
## test-pipeline-nonstandard
## version 0.0.1 - initial
##################################################
shopt -s expand_aliases
alias handle-nonstandard-pipepline-error='
{
  case ${str} in
   error*) {
    echo ${str} 1>&2
    echo exiting ${FUNCNAME} ... 1>&2
   } ;;
   *) {
     payload
   } ;;
  esac
}
'
upper() { { local str ; read str ; }
  payload() { 
    echo ${str^^}
  }
  handle-nonstandard-pipepline-error
}
lower() { { local str ; read str ; }
  _
  payload() {
    echo ${str,,}
  }
  handle-nonstandard-pipepline-error
}
test-pipeline-nonstandard() {
  echo pipeline with error in lower
  _() { echo error in lower 1>&2 ; }
  echo ${@} |& lower |& upper
  echo " "
  echo pipeline without error in lower 
  _() { true ; }
  echo ${@} |& lower |& upper
}
##################################################
if [ ! ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-pipeline-nonstandard ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on Tue, 23 Jul 2019 13:28:31 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
