#!/bin/bash
## test-pipeline-time
## version 0.0.1 - initial
##################################################
func() {
  x+=1
  sleep 1
  sleep $(( RANDOM % 2 ))
  false
}
test-pipeline-time() {
  time func
  echo -e "exit status: ${?} \nx: ${x}"
  time ! func
  echo -e "exit status: ${?} \nx: ${x}"

}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-pipeline-time
##################################################
## generated by create-stub2.sh v0.1.2
## on Mon, 22 Jul 2019 13:49:57 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
