#!/bin/bash
## test-xargs-mv-with-rename
## version 0.0.1 - initial
##################################################
test-xargs-mv-with-rename() {
  touch {1..5}
  echo -n {1..5} | xargs '-d ' -i mv -v {}{,-1}
  rm -v {1..5}-1
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-xargs-mv-with-rename
##################################################
## generated by create-stub2.sh v0.1.2
## on Sun, 28 Jul 2019 21:46:01 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
