#!/bin/bash
## test-dynamic-function-second
## version 0.0.1 - initial
##################################################
test-dynamic-function-second() {
  local temp
  temp=$( mktemp )
  cat > ${temp} << EOF
${function_name}() {
  echo \${FUNCNAME}
}
EOF
  . ${temp}
  declare -pf ${function_name}
  ${function_name}
  rm -v ${temp}
}
##################################################
if [ ${#} -eq 1 ] 
then
 function_name="${1}"
else
 exit 1 # wrong args
fi
##################################################
test-dynamic-function-second
##################################################
## generated by create-stub2.sh v0.1.2
## on Sun, 07 Jul 2019 10:56:38 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
