#!/bin/bash
## test-pipelines-mixed
## version 0.0.1 - initial
##################################################
shopt -s expand_aliases
alias handle-nonstandard-pipepline-error='
{
  case ${str} in
   error*) {
     echo ${str} on line $(( RANDOM % LINENO )) >> ${temp}-error-log # handle error
     payload
   } ;;
   *) {
     payload
   } ;;
  esac
}
'
## see also test-pipeline-nonstandard.sh
banner() {
      cat << EOF
205f20202020202020202020202020202020202020202020205f20202020
2020202020202020202020202020202020205f5f5f5f5f200a7c207c5f20
5f5f5f205f205f5f205f5f5f20205f205f5f207c207c5f205f5f5f205f20
5f5f205f5f5f20205f205f5f7c5f5f5f202f200a7c205f5f2f205f205c20
275f2060205f205c7c20275f205c7c205f5f2f205f205c20275f2060205f
205c7c20275f205c207c5f205c200a7c207c7c20205f5f2f207c207c207c
207c207c207c5f29207c207c7c20205f5f2f207c207c207c207c207c207c
5f29207c5f5f29207c0a205c5f5f5c5f5f5f7c5f7c207c5f7c207c5f7c20
2e5f5f2f205c5f5f5c5f5f5f7c5f7c207c5f7c207c5f7c202e5f5f2f5f5f
5f5f2f200a2020202020202020202020202020202020207c5f7c20202020
20202020202020202020202020202020207c5f7c2020202020202020200a
EOF
}
decode() {
  xxd -ps -r
}
func() { read str
  payload() {
    banner | decode
  }
  handle-nonstandard-pipepline-error
}
test-pipelines-mixed() {
  local temp
  temp=$( mktemp )
  banner > ${temp}-banner
  for row in $( seq $( cat ${temp}-banner | wc -l ) )
  do
   { echo error in ${FUNCNAME} 1>&2 ; } |& func | sed -n "${row}p" 
  done
  echo =error-log=
  cat ${temp}-error-log | head -n 3
  echo ...
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-pipelines-mixed
##################################################
## generated by create-stub2.sh v0.1.2
## on Wed, 24 Jul 2019 13:43:26 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
