#!/bin/bash
## test-pipefail
## version 0.0.1 - initial
##################################################
func2() {
  echo ${x}
  x=0
}
func() {
  test ! $(( RANDOM % 3 )) -eq 0 || return ${1}
}
test-pipefail() {
  shopt -s lastpipe
  set -o pipefail
  declare -i x=0
  func 1 | func 2 | func 3 | func 4 | func 5 ; echo ${?}
  func 1 | func 2 | func 3 | func 4 | func 5 ; echo ${?}
  func 1 | func 2 | func 3 | func 4 | func 5 ; echo ${?}
  func 1 | func 2 | func 3 | func 4 | func 5 ; echo ${?}
  func 1 | func 2 | func 3 | func 4 | func 5 ; echo ${?}
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-pipefail
##################################################
## generated by create-stub2.sh v0.1.2
## on Mon, 22 Jul 2019 21:31:47 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
