#!/bin/bash
## test-once
## version 0.0.1 - initial
##################################################
once() { 
  once() { 
    true
  }
  echo ${FUNCNAME}
}
test-once() {
  once
  once
  once
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-once
##################################################
## generated by create-stub2.sh v0.1.2
## on Tue, 02 Jul 2019 21:45:57 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
