#!/bin/bash
## test-pipelines-lastpipe
## version 0.0.1 - initial
##################################################
func2() {
  x=0
}
func() {
  x+=1
}
test-pipelines-lastpipe() {
  x=0
  func | func | func | func
  echo ${x}
  func2 | func | func | func
  echo ${x}
  func | func2 | func | func
  echo ${x}
  func | func | func2 | func
  echo ${x}
  func | func | func | func2
  echo ${x}
  echo enabling lastpipe ...
  shopt -s lastpipe
  func | func | func | func
  echo ${x}
  func2 | func | func | func
  echo ${x}
  func | func2 | func | func
  echo ${x}
  func | func | func2 | func
  echo ${x}
  func | func | func | func2
  echo ${x}
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-pipelines-lastpipe
##################################################
## generated by create-stub2.sh v0.1.2
## on Sun, 21 Jul 2019 21:28:54 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
