#!/bin/bash
## test-pipeline-negation
## version 0.0.1 - initial
##################################################
func2() {
  x=0
}
func() {
  x+=1
  false 
}
test-pipeline-negation() {
  func
  echo exit status: ${?}
  echo x: ${x}
  echo negating function ...
  ! func 
  echo exit status: ${?}
  echo x: ${x}
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-pipeline-negation
##################################################
## generated by create-stub2.sh v0.1.2
## on Mon, 22 Jul 2019 13:36:01 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
