#!/bin/bash
## test-export-array
## version 0.0.1 - initial
##################################################
test-export-array() {
  declare -p arr 2>/dev/null && return
  declare -p int 2>/dev/null && return
  shopt -s lastpipe
  declare -ax arr
  declare -ix int
  seq 10 | mapfile -t arr
  int=${#arr[@]}
  declare -p arr
  declare -p int
  bash ${0}
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-export-array
##################################################
## generated by create-stub2.sh v0.1.2
## on Fri, 26 Jul 2019 22:25:37 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
