#!/bin/bash
## test-function-exit
## version 0.0.1 - initial
##################################################
set -e # errexit
trap exit EXIT
exit() {
  builtin exit ${?}
}
test-function-exit() {
  echo noise
  ( return 0 )
  echo silence
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-function-exit
##################################################
## generated by create-stub2.sh v0.1.2
## on Mon, 08 Jul 2019 19:50:33 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
