#!/bin/bash
## test-function-positional-parameter-count
## version 0.0.1 - initial
##################################################
func() {
  echo There are ${#} positional parameter$( test ! ${#} -gt 1 || echo s )
  for i in $( seq ${#} )
  do
  echo \${${i}} is ${@:i:1}
  done
}
test-function-positional-parameter-count() {
  func $( seq $(( RANDOM % 100 )) | sort --random-sort )
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-function-positional-parameter-count
##################################################
## generated by create-stub2.sh v0.1.2
## on Sun, 21 Jul 2019 20:37:44 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
